name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker-mirror.powerhome.top", custom_domain = true },
  { pattern = "docker-hub.powerhome.top", custom_domain = true },
  { pattern = "quay.powerhome.top", custom_domain = true },
  { pattern = "gcr.powerhome.top", custom_domain = true },
  { pattern = "k8s-gcr.powerhome.top", custom_domain = true },
  { pattern = "k8s.powerhome.top", custom_domain = true },
  { pattern = "ghcr.powerhome.top", custom_domain = true },
  { pattern = "cloudsmith.powerhome.top", custom_domain = true },
  { pattern = "docker-auth.powerhome.top", custom_domain = true },
  { pattern = "18c.powerhome.top", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.powerhome.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
